// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDquG8vbDpk9tf4-Zzuz4tiD3B1lqETEhI',
    appId: '1:669802372204:android:193742831c909ae3f7cc49',
    messagingSenderId: '669802372204',
    projectId: 'clean-and-green-eco',
    databaseURL: 'https://clean-and-green-eco-default-rtdb.firebaseio.com',
    storageBucket: 'clean-and-green-eco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRT49UeKEfXWW1c3SIw0i8veBmiSw8EZ8',
    appId: '1:669802372204:ios:a76e04a43d6c0c71f7cc49',
    messagingSenderId: '669802372204',
    projectId: 'clean-and-green-eco',
    databaseURL: 'https://clean-and-green-eco-default-rtdb.firebaseio.com',
    storageBucket: 'clean-and-green-eco.appspot.com',
    iosClientId: '669802372204-7j5fqhdag3ih4t9ti3308al610a3h4h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanAndGreen',
  );
}
